export const TOPICS_PEDIATRIC_ORTHOPAEDICS = [
  "Supracondylar Fracture – Pediatric",
  "Pediatric Osteomyelitis",
  "Developmental Dysplasia of Hip",
  "Slipped Capital Femoral Epiphysis",
  "Pediatric Abuse",
  "Pediatric Femoral Shaft Fracture",
  "Pediatric Hip Septic Arthritis",
  "Tarsal Coalition",
  "Neurofibromatosis",
  "Clubfoot",
  "Leg Length Discrepancy",
  "Obstetric Brachial Plexopathy",
  "Distal Femoral Physeal Fractures",
  "Charcot–Marie–Tooth Disease",
  "Duchenne Muscular Dystrophy",
  "Achondroplasia",
  "Osteogenesis Imperfecta",
  "Infantile Blount Disease",
  "Physeal Considerations",
  "Medial Epicondyle Fracture – Pediatric",
  "Cavovarus Foot",
  "Proximal Femur Fracture – Pediatric",
  "Tibial Eminence Fracture",
  "Distal Radius Fracture – Pediatric",
  "Lateral Condyle Fracture – Pediatric",
  "Tibial Tubercle Fracture",
  "Cerebral Palsy – General",
  "Myelodysplasia",
  "Congenital Vertical Talus",
  "Spinal Muscular Atrophy",
  "Cerebral Palsy – Gait Disorders",
  "Marfan Syndrome",
  "Osteopetrosis",
  "Tibial Shaft Fracture – Pediatric",
  "Both Bone Forearm Fracture – Pediatric",
  "Cerebral Palsy – Hip Disorders",
  "Pediatric Ankle Fractures",
  "Accessory Navicular",
  "Kohler Disease",
  "Perthes Disease",
  "Lyme Disease",
  "Distal Humerus Physeal Separation",
  "Radial Head & Neck Fracture – Pediatric",
  "Monteggia Fracture – Pediatric",
  "Proximal Tibia Metaphyseal Fracture",
  "Tillaux Fracture",
  "Posteromedial Tibial Bowing",
  "Mucopolysaccharidoses",
  "Proximal Humerus Fracture – Pediatric",
  "Sever Disease",
  "Pediatric Trauma Evaluation",
  "Pediatric Pelvic Fractures",
  "Adolescent Blount Disease",
  "Fibular Deficiency",
  "Congenital Pseudoarthrosis of Tibia",
  "Femoral Anteversion",
  "Internal Tibial Torsion",
  "Flexible Flatfoot",
  "Arthrogryposis",
  "Down Syndrome",
  "Pediatric Humeral Shaft Fracture",
  "Pediatric Elbow Dislocation",
  "Triplane Fracture",
  "Cleidocranial Dysplasia",
  "Transient Synovitis of Hip",
  "Sprengel Deformity",
  "Proximal Femoral Focal Deficiency",
  "Multiple Epiphyseal Dysplasia",
  "Diastrophic Dysplasia",
  "Distal Clavicle Physeal Fracture",
  "Pediatric Olecranon Fracture",
  "Proximal Tibia Epiphyseal Fracture",
  "Sacral Agenesis",
  "Congenital Knee Dislocation",
  "Bipartite Patella",
  "Genu Valgum",
  "Polydactyly of Foot",
  "Nursemaid’s Elbow",
  "Pediatric Traumatic Hip Dislocation",
  "Coxa Vara",
  "Tibial Deficiency",
  "Metatarsus Adductus",
  "Calcaneovalgus Foot",
  "Congenital Curly Toe",
  "Friedreich Ataxia",
  "Larsen Syndrome",
  "Spondyloepiphyseal Dysplasia",
  "Beckwith–Wiedemann Syndrome",
  "Epiphyseal Bracket",
  "Pediatric Clavicle Shaft Fracture",
  "Pediatric SI Joint Infection",
  "CRMO",
  "Congenital Pseudoarthrosis of Clavicle",
  "Congenital Patellar Dislocation",
  "Popliteal Cyst – Pediatric",
  "Syndactyly of Toes",
  "Overlapping Toe",
  "Brachymetatarsia",
  "Local Gigantism",
  "Rett Syndrome",
  "Trevor Disease",
  "Bladder Exstrophy",
  "Gaucher Disease",
  "Pediatric Psoas Abscess",
  "Congenital Popliteal Webbing",
];
