export const TOPICS_FOOT_ANKLE = [
  "Hallux Valgus",
  "Posterior Tibial Tendon Insufficiency",
  "Ankle Sprain",
  "Lisfranc Injury",
  "Hallux Rigidus",
  "Achilles Tendon Rupture",
  "Diabetic Foot Ulcers",
  "Peroneal Tendon Tears",
  "5th Metatarsal Base Fracture",
  "Foot Muscle Forces & Deformities",
  "Charcot Foot",
  "Ankle Arthrodesis",
  "Ankle Arthritis",
  "Achilles Tendonitis",
  "Osteochondral Lesions of Talus",
  "Bunionette Deformity",
  "Syndesmotic Injury",
  "Morton Neuroma",
  "Ankle Arthroscopy",
  "Ankle Ligaments",
  "Claw Toe",
  "Plantar Fasciitis",
  "Foot Puncture Wounds",
  "Navicular Fractures",
  "Tarsal Tunnel Syndrome",
  "Total Ankle Arthroplasty",
  "Freiberg Disease",
  "Metatarsal Fractures",
  "Midfoot Arthritis",
  "Leg Nerve Entrapment Syndromes",
  "Lower Extremity Ossicles",
  "Gait Cycle",
  "Sesamoid Injuries",
  "MTP Dislocations",
  "FHL Tendon Injury",
  "Turf Toe",
  "Foot Nerves",
  "Foot Anatomy & Biomechanics",
  "Hallux Varus",
  "Hammer Toe",
  "Tibiotalar Impingement",
  "Anterior Tibialis Tendon Rupture",
  "2nd MTP Synovitis",
  "Poliomyelitis",
  "Orthotics",
  "Spastic Equinovarus Deformity",
  "Deep Peroneal Nerve Entrapment",
  "Blood Supply to Foot",
];
