export const TOPICS_BASIC_SCIENCE_PATIENT_KNOWLEDGE = [
  "Legal Issues in Orthopaedics",
  "Statistics Explained",
  "Osteopenia & Osteoporosis",
  "Rheumatoid Arthritis",
  "Material Properties",
  "Orthopaedic Implants",
  "Bone Grafting",
  "Articular Cartilage",
  "Fracture Healing",
  "Antibiotics",
  "Anticoagulants",
  "Ethics in Medicine",
  "DVT & PE Prevention",
  "Rickets",
  "Bisphosphonates",
  "Clinical Trials",
  "Complex Regional Pain Syndrome",
  "Bone Cells",
  "Bone Signaling",
  "Genetic Disorders",
  "Gout",
  "Rehabilitation & Prosthetics",
  "Anaesthesia",
  "Bone Growth Factors",
  "Anti-inflammatory Drugs",
  "Evidence-Based Medicine",
  "Tendons",
  "Muscle Biology",
  "Nonunion",
  "Occupational Health",
  "Outcome Measures",
  "Bone Remodeling",
  "Genetic Pearls",
  "Pain Medications",
  "Juvenile Idiopathic Arthritis",
  "Sickle Cell Disease",
  "Molecular Biology",
  "Endochondral Ossification",
  "Medical Billing",
  "Ligaments",
  "Surgical Antibiotic Prophylaxis",
  "PRP",
  "Hemophilia",
  "Collagen",
  "Psoriatic Arthritis",
  "Fat Embolism Syndrome",
  "Immunology",
  "Embryology",
  "Vitamin D & PTH",
  "Renal Osteodystrophy",
  "Hyperparathyroidism",
  "Bone Metabolism",
  "Cartilage Biology",
  "Hypophosphatasia",
  "DVT",
  "Pseudogout",
  "Bone Matrix",
  "Synovial Fluid",
  "Hemophilic Arthropathy",
  "Blood Transfusion",
  "Informed Consent",
  "Bone Circulation",
  "Ochronosis",
  "Lead Toxicity",
  "Intramembranous Ossification",
  "Hypoparathyroidism",
  "Scurvy",
  "ALS",
  "Structural Properties",
  "Myasthenia Gravis",
  "Bioabsorbable Materials",
  "Multiple Sclerosis",
  "Scleroderma",
  "Career Development",
];
