export const TOPICS_HAND_WRIST = [
  "Carpal Tunnel Syndrome",
  "Peripheral Nerve Injury & Repair",
  "Flexor Tendon Injuries",
  "Scaphoid Fracture",
  "Fingertip Amputation & Finger Flaps",
  "Phalanx Fractures",
  "Basilar Thumb Arthritis",
  "Kienbock Disease",
  "Cubital Tunnel Syndrome",
  "Metacarpal Fractures",
  "Phalanx Dislocations",
  "Dupuytren Disease",
  "Replantation",
  "SLAC Wrist",
  "Extremity Flap Reconstruction",
  "Ganglion Cysts",
  "Perilunate Dislocation",
  "Radial Clubhand",
  "Hook of Hamate Fracture",
  "DIP & PIP Joint Arthritis",
  "MCP Dislocations",
  "Ulnar Tunnel Syndrome",
  "Pyogenic Flexor Tenosynovitis",
  "Mallet Finger",
  "Scapholunate Ligament Injury",
  "TFCC Injury",
  "Scaphoid Nonunion",
  "Quadriga Effect",
  "Constrictive Ring Syndrome",
  "High Pressure Injection Injury",
  "Flexor Pulley System",
  "Jersey Finger",
  "De Quervain Tenosynovitis",
  "Extensor Tendon Injuries",
  "Tendon Transfer Principles",
  "Giant Cell Tumor of Tendon Sheath",
  "SNAC Wrist",
  "AIN Compression Syndrome",
  "PIN Compression Syndrome",
  "Radial Tunnel Syndrome",
  "Trigger Finger",
  "Sagittal Band Rupture",
  "Base of Thumb Fractures",
  "Thumb Collateral Ligament Injury",
  "Polydactyly of Hand",
  "Congenital Trigger Thumb",
  "Raynaud Syndrome",
  "Frostbite",
  "Wrist Ligaments",
  "Wrist Arthroscopy",
  "Snapping ECU",
  "Ulnocarpal Abutment Syndrome",
  "Congenital Radioulnar Synostosis",
  "Hypothenar Hammer Syndrome",
  "Thumb CMC Dislocation",
  "Seymour Fracture",
  "Intrinsic Plus Hand",
  "Intersection Syndrome",
  "Madelung Deformity",
  "Poland Syndrome",
  "Thumb Hypoplasia",
  "Dog & Cat Bites",
  "MCP Joint Arthritis",
  "Claw Hand",
  "Pronator Syndrome",
  "Ulnar Styloid Impaction",
  "Wrist Arthritis",
  "Congenital Radial Head Dislocation",
  "Apert Syndrome",
  "Hand Blood Supply",
  "Hand Physical Examination",
  "Boutonniere Deformity",
  "Swan Neck Deformity",
  "CIND",
  "Ulnar Variance",
  "Gymnast Wrist",
  "Camptodactyly",
  "Felon",
  "Human Bite",
  "Nail Bed Injury",
  "Pisiform Fracture",
  "Nerve Conduction Studies",
  "Subclavian Artery Thrombosis",
  "Finger Ligaments",
  "Extensor Compartments",
  "Lumbrical Plus Finger",
  "Wartenberg Syndrome",
  "FCR Tendinitis",
  "Digital Collateral Ligament Injury",
  "Lunotriquetral Ligament Injury",
  "Preiser Disease",
  "Skin Grafting",
  "Cleft Hand",
  "Syndactyly",
  "Macrodactyly",
  "Congenital Clasped Thumb",
  "Epidermal Inclusion Cyst",
  "Buerger Disease",
  "Deep Space Hand Infections",
  "Atypical Mycobacterial Infection",
  "Digital Artery Aneurysm",
  "Wrist Trauma Radiographic Evaluation",
  "Triquetrum Fracture",
  "Radiocarpal Fracture Dislocation",
];
