export const TOPICS_PATHOLOGY_ORTHOPAEDIC_ONCOLOGY = [
  "Metastatic Bone Disease – Extremity",
  "Chondrosarcoma",
  "Osteosarcoma",
  "Giant Cell Tumor",
  "Soft Tissue Sarcoma",
  "Osteochondroma",
  "Metastatic Spine Disease",
  "Ewing Sarcoma",
  "Enchondroma",
  "Pigmented Villonodular Synovitis",
  "Paget Disease of Bone",
  "Unicameral Bone Cyst",
  "Liposarcoma",
  "Osteoid Osteoma",
  "Aneurysmal Bone Cyst",
  "Synovial Sarcoma",
  "Non-Ossifying Fibroma",
  "Fibrous Dysplasia",
  "Chondroblastoma",
  "Biopsy Principles",
  "Multiple Myeloma",
  "Heterotopic Ossification",
  "Periosteal Osteosarcoma",
  "Myositis Ossificans",
  "Parosteal Osteosarcoma",
  "Lymphoma of Bone",
  "Schwannoma",
  "Lipoma",
  "Eosinophilic Granuloma",
  "Adamantinoma",
  "Desmoid Tumor",
  "Chordoma",
  "Undifferentiated Pleomorphic Sarcoma",
  "Soft Tissue Hemangioma",
  "Squamous Cell Carcinoma",
  "Chondromyxoid Fibroma",
  "Osteofibrous Dysplasia",
  "Synovial Chondromatosis",
  "Epithelioid Sarcoma",
  "Impending Fracture",
  "Chemotherapy",
  "Radiation Therapy",
  "Rhabdomyosarcoma",
  "Melanoma",
  "Bone Tumor Staging",
  "Pleomorphic Sarcoma of Bone",
  "Neurofibroma",
  "Tumoral Calcinosis",
  "Osteoblastoma",
  "Telangiectatic Osteosarcoma",
  "Hemangioma",
  "Melorheostosis",
  "Malignant Peripheral Nerve Sheath Tumor",
  "Dermatofibrosarcoma Protuberans",
  "Glomus Tumor",
  "Periosteal Chondroma",
  "Leiomyosarcoma",
  "Plantar Fibromatosis",
  "Bone Infarct",
  "Intramuscular Myxoma",
  "Leukemia",
  "Nodular Fasciitis",
  "Angiosarcoma",
  "Focal Fibrocartilaginous Dysplasia",
  "Neuroblastoma",
];
