export const TOPICS_ANATOMY_PATIENT_REFERENCE = [
  "Sciatic Nerve",
  "Subscapularis",
  "Radial Nerve",
  "Posterior Interosseous Nerve",
  "Axillary Nerve",
  "Biceps Brachii",
  "Psoas Muscle",
  "Adductor Longus",
  "Piriformis",
  "Peroneus Brevis",
  "Median Nerve",
  "Ulnar Nerve",
  "Lumbosacral Plexus",
  "Superficial Peroneal Nerve",
  "Pectoralis Major",
  "Teres Major",
  "Brachialis",
  "Flexor Pollicis Longus",
  "Extensor Indicis Proprius",
  "Abductor Digiti Minimi",
  "Lumbricals",
  "Brachial Plexus",
  "Iliacus",
  "Sartorius",
  "Gluteus Medius",
  "Semimembranosus",
  "Biceps Femoris (Short Head)",
  "Obturator Internus",
  "Extensor Digitorum Longus",
  "Peroneus Tertius",
  "Popliteus",
  "Flexor Hallucis Longus",
  "Musculocutaneous Nerve",
  "Anterior Interosseous Nerve",
  "Femoral Nerve",
  "Quadrangular Space",
];
